services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  web:
    build: .
    command: bash -c "wait-for-it db 5432 -- yarn build && yarn build:css && bundle exec rails server -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432
      RAILS_ENV: development
      POSTGRES_PASSWORD: postgres
    depends_on:
      - db

volumes:
  postgres_data:
  node_modules: